Path2
Mazebug/debug pull request #5
Opened 2020-06-27 14:58 UTC by Mazebug

第二题前五份完成

2020-06-27 15:20 UTC, YXxx1122 commented on 2/4.txt
> +                printf("%d ", m3[i][j]);
这个测试memset不需要打印出来。

2020-06-27 15:27 UTC, YXxx1122 commented on 2/5.txt
> +                for (k = 0; k < m; k++) {
这里应该是k<n

2020-06-27 15:27 UTC, YXxx1122 commented on 2/5.txt
> +                if(j == n-1) {
这里应该是j==m-1

2020-06-27 15:29 UTC, YXxx1122 commented
不太确定最后一行末尾要不要换行，不过这是小意思，可以到时再改。就有几个小错改了就好

2020-06-27 15:35 UTC, YXxx1122 requested changes
害 我操作不太熟 是不是重复发了好多邮件嗷 就几个小错

2020-06-27 15:39 UTC, Mazebug commented on 2/4.txt
> +                printf("%d ", m3[i][j]);
memset没打印昂；只是给m3初始化了一下

2020-06-27 15:51 UTC, Mazebug commented on 2/5.txt
> +                for (k = 0; k < m; k++) {
已改

2020-06-27 15:51 UTC, Mazebug commented on 2/5.txt
> +                if(j == n-1) {
改好啦

2020-06-27 15:52 UTC, Mazebug commented
除了第一个memset不太清楚你的意思之外其他地方都改啦(*^▽^*)

2020-06-28 10:33 UTC, YXxx1122 approved these changes

2020-06-28 10:33 UTC, merged